apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # Optional: Use Network Load Balancer for faster access
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
