apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins
          image: arjun16/jenkins-docker-kubectl:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
        - name: docker-dind
          image: docker:20.10-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args: ["--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2", "--tls=false"]
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home-pvc
        - name: dind-storage
          persistentVolumeClaim:
            claimName: dind-storage-pvc

